module.exports = function (x, y) {
  this.board = board
  if (arguments.length === 0) return this.board
  if (!validate(arguments)) throw new Error('Only integers 0 - 14 are valid')
  if (arguments.length === 1) return this.board[x]
  if (arguments.length === 2) return this.board[x][y]
}
function validate(arguments) {
  return Array.prototype.slice.call(arguments).every(function (arg) {
    return Number.isInteger(arg) && arg >= 0 && arg <= 14
  })
}
var board = [
    [ //row a
     { LS:1, WS:3 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:2, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:3 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:2, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:3 }
    ],
    [ //row b
     { LS:1, WS:1 },
     { LS:1, WS:2 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:3, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:3, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:2 },
     { LS:1, WS:1 }
    ],
     [ //row c
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:2 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:2, WS:1 },
     { LS:1, WS:1 },
     { LS:2, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:2 },
     { LS:1, WS:1 },
     { LS:1, WS:1 }
    ],
    [ //row d
     { LS:2, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:2 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:2, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:2 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:2, WS:1 }
    ],
    [ //row e
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:2 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:2 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 }
    ],
    [ //row f
     { LS:1, WS:1 },
     { LS:3, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:3, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:3, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:3, WS:1 },
     { LS:1, WS:1 }
    ],
    [ //row g
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:2, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:2, WS:1 },
     { LS:1, WS:1 },
     { LS:2, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:2, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 }
    ],
    [ //row h
     { LS:1, WS:3 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:2, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:2, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:3 }
    ],
    [ //row i
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:2, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:2, WS:1 },
     { LS:1, WS:1 },
     { LS:2, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:2, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 }
    ],
    [ //row j
     { LS:1, WS:1 },
     { LS:3, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:3, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:3, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:3, WS:1 },
     { LS:1, WS:1 }
    ],
    [ //row k
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:2 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:2 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 }
    ],
    [ //row l
     { LS:2, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:2 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:2, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:2 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:2, WS:1 }
    ],
    [ //row m
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:2 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:2, WS:1 },
     { LS:1, WS:1 },
     { LS:2, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:2 },
     { LS:1, WS:1 },
     { LS:1, WS:1 }
    ],
    [ //row n
     { LS:1, WS:1 },
     { LS:1, WS:2 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:3, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:3, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:2 },
     { LS:1, WS:1 }
    ],
    [ //row o
     { LS:1, WS:3 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:2, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:3 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:2, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:1 },
     { LS:1, WS:3 }
    ]
  ]